
Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false
Lint/AssignmentInCondition:
  Description: "Don't use assignment in conditions."
  Enabled: false
Style/BlockComments:
  Enabled: false
